name: Deploy Frontend to ECS

on:
  push:
    branches: [main]
    paths:
      - 'university-student-service/frontend/student-portal/**'
  workflow_dispatch:        

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:        
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
            
      - name: Build and tag Docker image
        run: |
          cd university-student-service/frontend/student-portal
          IMAGE_NAME=062365602724.dkr.ecr.ap-southeast-2.amazonaws.com/studentportal-frontend
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker images to ECR
        run: |
          cd university-student-service/frontend/student-portal
          IMAGE_NAME=062365602724.dkr.ecr.ap-southeast-2.amazonaws.com/studentportal-frontend
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
          

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: frontend-task-def.json
          service: studentportal-frontend-task-service-4cfl7ymw
          cluster: student-university-cluster
          wait-for-service-stability: true
